### ISSUE TITLE
gh-pages not working: 404

### ISSUE THREAD

**Issue by mcanthony** [surunzi/VisualMusic#1]
I am not sure why since the required files seem to be in place and the URL is correct, but the github page returns a 404 not found. I will of course just test it locally instead, but I thought I would let you know do you might investigate the issue. One guess is gh-pages is not enabled in your setting for this repo or your account (not sure how it all works).

**Comment by surunzi** [comment]
Don't know why the gh-pages suddenly broke. I made a little change to one file and commit it to gh-pages branch. To my surprise, that fix the problem, kind of weird.
