### ISSUE TITLE
动画的波动是以声波波动的吗，请问使用的是audio的哪个api

### ISSUE THREAD

**Issue by eyasliu** [surunzi/VisualMusic#2]
我不记得html 的 audio 有这个api，请问有相关的文档吗

**Comment by surunzi** [comment]
@eyasliu 完整的Web Audio Api，还是草案：https://webaudio.github.io/web-audio-api/

这个项目只用了里面一点东西，全在这个文件里：
https://github.com/surunzi/VisualMusic/blob/master/js/analyser.js

**Comment by eyasliu** [comment]
thank you very much
